plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.bibleproia.app'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.bibleproia.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.browser:browser:1.8.0'
}
